### PR TITLE
fix: logo text style

### LINKED ISSUE #221: Lingering Design issues flagged by Martin
@rafaelramalho19  would we be able to fix some of the items listed in teh figma here: https://www.figma.com/file/826Zurcs6kgWSzQ35it966?node-id=2062:565#97496011

There's a design element that's also apparently broken here: https://www.figma.com/file/826Zurcs6kgWSzQ35it966?node-id=1396:565#97499406

### PR DESCRIPTION
**Pull request by rafaelramalho19**
Closes #221

### CODE REVIEW

File: packages/website/components/navbar.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ export default function Navbar({ bgColor = '', isLoggedIn, isLoadingUser }) {
             onClick={onLinkClick}
           >
             <img src="/w3storage-logo.svg" style={{ height: '1.8rem' }} />
-            <span className="space-grotesk ml-2 text-w3storage-purple font-medium text-md hidden xl:inline-block">Web3.Storage</span>
+            <span className="space-grotesk ml-2 text-w3storage-purple font-medium typography-logo hidden xl:inline-block">Web3.Storage</span>
```
Comment (jdiogopeixoto) [inline packages/website/components/navbar.js:42]: You can just use `text-base` instead of adding a new typography class

**Review by jdiogopeixoto — CHANGES_REQUESTED** [review]

File: packages/website/components/navbar.js (hunk 1 above)
Comment (rafaelramalho19) [reply packages/website/components/navbar.js:42]: You're right, didn't see the text-base, my bad :)

**Review by jdiogopeixoto — APPROVED** [review]

**Review by alanshaw — APPROVED** [review]
