### PR TITLE
fix: update pin status from GET /pins even if failed

### LINKED ISSUE #2234: getPin should update pin status to failed if upstream says its failed
We previously avoided setting a pin status to failed as cluster would periodically retry to fetch things. pickup wont do that, so we should let the user know early and set the failed status when the upstream says it's failed.

### PR DESCRIPTION
**Pull request by olizilla**
Update pin status for pins regardless of status. Previously we only updated if the state was positive.

Pickup will not retry pins that timeout, so the change here ensures we inform users promptly where that happens.

Where the user has a pending pin, the request will now synchronously go check cluster/pickup, update the db and return the response. Previously the worker would respond early, and poll for a positive pin status from the upstream for up to 30s. Just checking the upstream once per request seems sufficient. We may want to rate limit this end point in the future, but it's pretty low volume currently.

fixes #2234 

License: MIT

### CODE REVIEW

File: packages/api/src/utils/pin.js [hunk 1]
```diff
@@ -155,15 +156,33 @@ export async function waitOkPins (cid, cluster, waitTime = MAX_PIN_STATUS_CHECK_
...
   return okPins
 }
+
+/**
+ * @param {string} contentCid
+ * @param {import('@web3-storage/db/db-client-types').PinUpsertInput[]} pins
+ * @returns {import('@web3-storage/db/db-client-types').PinsUpsertInput[]}
+ */
+export function toPinsUpsert (contentCid, pins) {
+  // @ts-ignore
```
Comment (olizilla) [inline packages/api/src/utils/pin.js:170]: in my defence, i have simply refactored and moved the @ts-ignore that was already there on line 166.

Comment (olizilla) [reply packages/api/src/utils/pin.js]: ah ha. Those types are only used in this file and id is not needed by the impl.

Comment (olizilla) [reply packages/api/src/utils/pin.js]: i have fixed

**Review by alanshaw — APPROVED** [review]
